extends SceneTree
var app: Node2D
var checks: Array[Dictionary] = []
const OUT := "res://reports/v0.3/"
func _initialize() -> void:
	call_deferred("run")
func frames(count: int) -> void:
	for _i in count:
		await physics_frame
		await process_frame
func check(label: String, passed: bool) -> void:
	checks.append({"check": label, "passed": passed})
	print(label, ": ", passed)
func shot(label: String) -> void:
	await RenderingServer.frame_post_draw
	root.get_texture().get_image().save_png(OUT + label + ".png")
func begin(selected_mode: String = "pursuit", selected_level: String = "relay_station") -> void:
	Input.action_release("move_right")
	Input.action_release("jump")
	app.set_physics_process(true)
	app.start_challenge(false, selected_mode, selected_level)
	Input.action_press("move_right")
	await frames(5)
	Input.action_release("move_right")
	await frames(2)
func stage(at: Vector2, front: float) -> void:
	app.player.reset_at(at)
	app._previous_position = at
	app.player.set_physics_process(false)
	app.camera.position = Vector2(at.x + 96, 270)
	app.camera.reset_smoothing()
	app.chase.front_x = front
	app.chase.grace_remaining = 0
	app.chase.advance(0, at.x - 10)
	app.ui.set_notice("", Color.WHITE)
	await frames(2)
func finish_fixture() -> void:
	app._on_goal(app.player)
	await frames(2)
func run() -> void:
	app = load("res://scenes/main/main.tscn").instantiate()
	root.add_child(app)
	await frames(6)
	check("menu_defaults_to_new_station", app.ui.selected_level == "relay_station")
	await shot("menu")
	app.ui.start_requested.emit()
	await frames(2)
	check("menu_enters_selected_station", app.level_id == "relay_station" and app.phase == "ready" and app.course.relays.size() == 2)
	await begin()
	check("production_layout_five_sections", app.course.section_starts.size() == 5 and app.course.course_length == 14500)
	check("swept_node_contact", app.course.relay_candidates(Vector2(2300, 314), Vector2(2700, 314)) == ["relay_one"])
	check("low_route_does_not_collect_high_node", app.course.relay_candidates(Vector2(2300, 433), Vector2(2700, 433)).is_empty())
	await stage(Vector2(2270, 385), 1880)
	await shot("first-branch")
	await stage(Vector2(2530, 314), 2180)
	await frames(2)
	check("real_overlap_collects_node", app.relay_count == 1)
	var old_front: float = app.chase.front_x
	var old_elapsed: float = app.elapsed
	await frames(12)
	check("relay_stops_front_not_clock", app.chase.front_x == old_front and app.elapsed > old_elapsed)
	check("delay_getter_synchronized", app.relay_delay_remaining == app.chase.relay_remaining)
	check("relay_visual_installed", app.world.has_node("RelayVisual"))
	await shot("relay-active")
	app.toggle_pause()
	await frames(2)
	var pause: Array = [app.elapsed, app.chase.front_x, app.relay_delay_remaining, app.world.get_node("RelayVisual").presentation_state().animation_time]
	await shot("pause-a")
	await frames(15)
	check("pause_freezes_delay_world_and_visual", pause == [app.elapsed, app.chase.front_x, app.relay_delay_remaining, app.world.get_node("RelayVisual").presentation_state().animation_time])
	await shot("pause-b")
	app.toggle_pause()
	await frames(60)
	check("front_resumes_after_relay", app.chase.front_x > old_front and is_zero_approx(app.relay_delay_remaining))
	await begin()
	app._queue_relay("relay_one")
	app._queue_relay("relay_one")
	app._queue_relay("relay_two")
	app._queue_relay("unknown")
	app.set_physics_process(false)
	await frames(1)
	check("two_nodes_once_total_1_8", app.relay_count == 2 and is_equal_approx(app.relay_delay_remaining, 1.8))
	app.set_physics_process(true)
	app.restart_challenge()
	check("restart_clears_all_relay_state", app.relay_count == 0 and app.relay_delay_remaining == 0 and app.course.relays.all(func(r): return not r.activated))
	app._queue_relay("relay_one")
	app.toggle_pause()
	await frames(2)
	check("pending_relay_held_during_pause", app.relay_count == 0)
	app.toggle_pause()
	await frames(2)
	check("pending_relay_resolves_on_resume", app.relay_count == 1)
	await begin()
	app._queue_relay("relay_one")
	app.player.die("spike")
	await frames(2)
	check("same_frame_death_beats_reward", app.phase == "failed" and app.relay_count == 0)
	await shot("failure")
	await begin("time_trial")
	app._queue_relay("relay_one")
	await frames(2)
	check("trial_counts_without_hold", app.relay_count == 1 and app.relay_delay_remaining == 0)
	app.player.die("spike")
	await frames(20)
	app._queue_relay("relay_one")
	await frames(2)
	check("trial_death_does_not_reset_nodes", app.phase == "running" and app.relay_count == 1)
	await finish_fixture()
	check("station_trial_score_saved", app.best_seconds > 0)
	await begin("pursuit")
	check("station_modes_isolated", app.best_seconds < 0)
	await finish_fixture()
	var station_best: float = app.best_seconds
	await begin("pursuit", "level01")
	check("level_scores_isolated", app.best_seconds < 0 and app.course.relays.is_empty())
	await finish_fixture()
	await begin("pursuit", "relay_station")
	check("station_best_retained", app.best_seconds == station_best)
	await stage(Vector2(8340, 315), 7940)
	await shot("second-branch")
	await stage(Vector2(14300, 430), 13780)
	await shot("goal")
	await finish_fixture()
	await shot("result")
	app.return_to_menu()
	app.ui.selected_level = "level01"
	app.ui.time_trial_requested.emit()
	await frames(2)
	check("original_menu_selection_works", app.level_id == "level01" and app.mode == "time_trial")
	app.start_challenge(true, "time_trial")
	await frames(2)
	check("lab_has_no_relay_counter", app.lab_mode and app.ui.relay_counter.text == "" and app.course.relays.is_empty())
	var passed := checks.all(func(c): return c.passed)
	var file := FileAccess.open(OUT + "integration-results.json", FileAccess.WRITE)
	file.store_string(JSON.stringify({"checks": checks, "passed": passed, "scope": "Graphical state/contact fixtures and UI callbacks; full input routes in route-results.json."}, "\t"))
	file.close()
	app.free()
	app = null
	OS.delay_msec(200)
	await frames(2)
	quit(0 if passed else 1)
